version: '2'
# docker login -e $(gcloud auth list | grep ACTIVE | grep qubeship.io | awk '{print $2}')  -u _token -p "$(gcloud auth print-access-token)" https://gcr.io
services:
  pypet:
    environment:
      DEFAULT_LISTENER_PORT: 8080
    image: pypet:latest
    ports:
      - 8080:8080
